# Site settings
title: Language Of Dimension T
header-img: img/home-bg.png
email: naveed@tayybah.com
copyright_name: ns5001
description: > # this means to ignore newlines until "baseurl:"
  Cool and informative blogs on tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ns5001
learn_profile: ns5001
email_username: naveed@tayybah.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
